version: "3.9"
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - 5432:5432
    networks:
      - magic_helper_network

  redis:
    image: redis:7.0.4-alpine
    container_name: redis
    command: [ sh, -c, "rm -f /data/dump.rdb && redis-server" ]
    env_file: ./.env
    depends_on:
      - postgres
    networks:
      - magic_helper_network

  webhook:
    build:
      context: .
      dockerfile: ./docker/webhook/Dockerfile
    container_name: webhook
    env_file: ./.env
    depends_on:
      - redis
    networks:
      - magic_helper_network

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - webhook
    ports:
      - 80:80
    networks:
      - magic_helper_network

networks:
  magic_helper_network:
    driver: bridge
    name: magic_helper_network

volumes:
  postgres-data:
